# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run ODE for constant PMR and gamma N.
#'
#' @param x0 Initial conditions for all stages (length should be `2*parms[5]`).
#' @param parms Vector of length 5 containing parameter values.
#'     Parameters in order: `cycleLength`, `mu`, `museq`, `R`, and `n`.
#' @param Maximum time point to simulate to.
#' @param Time step to use for ODE.
#'
#'
#' @export
#'
#' @return Numeric matrix where rows are time and columns are stages.
#'
constPMR_gammaN_ode <- function(x0, parms, max_t, dt) {
    .Call(`_estimatePMR_constPMR_gammaN_ode`, x0, parms, max_t, dt)
}

