# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Produce a vector of starting abundances based on a symmetrical beta distribution
#'
#' @param shape Single numeric giving the Beta distribution shape parameter.
#' @param offset Single numeric giving the Beta distribution offset parameter.
#' @param total0 Single numeric giving the total abundance across all stages.
#' @param compartments Integer giving the number of compartments for
#'     stage structure.
#'
#' @export
#'
beta_starts <- function(shape, offset, total0, compartments) {
    .Call(`_estimatePMR_beta_starts`, shape, offset, total0, compartments)
}

#' Run ODE for constant PMR and gamma N.
#'
#' @param x0 Initial conditions for all stages (length should be `2*parms[5]`).
#' @param parms Vector of length 5 containing parameter values.
#'     Parameters in order: `cycleLength`, `mu`, `museq`, `R`, and `n`.
#' @param Maximum time point to simulate to.
#' @param Time step to use for ODE.
#'
#'
#' @export
#'
#' @return Numeric matrix where rows are time and columns are stages.
#'
constPMR_gammaN_ode <- function(x0, parms, max_t, dt) {
    .Call(`_estimatePMR_constPMR_gammaN_ode`, x0, parms, max_t, dt)
}

